<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace Spryker\Zed\Configuration;

use Spryker\Shared\Configuration\ConfigurationConfig as ConfigurationConfigurationConfig;
use Spryker\Zed\Kernel\AbstractBundleConfig;

/**
 * @method \Spryker\Shared\Configuration\ConfigurationConfig getSharedConfig()
 */
class ConfigurationConfig extends AbstractBundleConfig
{
    /**
     * Specification:
     * - Returns directory paths relative to the application root where project-level YAML configuration schemas are located.
     * - Project schemas override core schemas at the setting key level during `configuration:sync`.
     *
     * @api
     *
     * @return array<string>
     */
    public function getProjectConfigSchemaPattens(): array
    {
        return [
            'data/configuration',
        ];
    }

    /**
     * Specification:
     * - Returns directory paths relative to each module root where vendor YAML configuration schemas are located.
     * - Scanned recursively for `*.configuration.yml` files during `configuration:sync`.
     *
     * @api
     *
     * @return array<string>
     */
    public function getCoreConfigSchemaPattens(): array
    {
        return [
            'resources/configuration',
        ];
    }

    /**
     * @api
     *
     * @internal Exists just to prevent code duplication for classes located in Shared folder.
     *
     * @return \Spryker\Shared\Configuration\ConfigurationConfig
     */
    public function getSharedModuleConfig(): ConfigurationConfigurationConfig
    {
        return $this->getSharedConfig();
    }

    /**
     * Specification:
     * - Returns the list of scope keys available for configuration management.
     * - Determines which scopes are shown in the Backoffice scope selector.
     * - Delegates to `ConfigurationConfig::getAvailableScopes()` in the Shared layer.
     *
     * @api
     *
     * @return array<string>
     */
    public function getAvailableScopes(): array
    {
        return $this->getSharedConfig()->getAvailableScopes();
    }

    /**
     * Specification:
     * - Returns the scope hierarchy as an associative array where each key is a scope and the value is its parent scope.
     * - The root scope (global) has `null` as parent.
     * - Used for value inheritance resolution: values walk up this hierarchy until a value is found.
     * - Delegates to `ConfigurationConfig::getScopeHierarchy()` in the Shared layer.
     *
     * @api
     *
     * @return array<string, string|null>
     */
    public function getScopeHierarchy(): array
    {
        return $this->getSharedConfig()->getScopeHierarchy();
    }

    /**
     * Specification:
     * - Returns the absolute file path where the merged configuration schema is cached as a PHP array.
     * - This file is generated by `configuration:sync` and read by the schema provider at runtime.
     * - Delegates to `ConfigurationConfig::getMergedSchemaFilePath()` in the Shared layer.
     *
     * @api
     *
     * @return string
     */
    public function getMergedSchemaFilePath(): string
    {
        return $this->getSharedConfig()->getMergedSchemaFilePath();
    }

    /**
     * Specification:
     * - Returns the absolute file path where the flat settings map is cached as a PHP array.
     * - Generated by `configuration:sync` alongside the merged schema.
     * - Delegates to `ConfigurationConfig::getSettingsMapFilePath()` in the Shared layer.
     *
     * @api
     *
     * @return string
     */
    public function getSettingsMapFilePath(): string
    {
        return $this->getSharedConfig()->getSettingsMapFilePath();
    }

    /**
     * Specification:
     * - Returns whether in-memory caching is enabled for configuration value reads.
     * - When enabled, values are cached per request to avoid repeated database queries.
     *
     * @api
     *
     * @return bool
     */
    public function isCacheEnabled(): bool
    {
        return true;
    }

    /**
     * Specification:
     * - Returns the encryption key used for encrypting and decrypting secret configuration values.
     * - Reads from environment configuration using `ConfigurationConstants::ENCRYPTION_KEY`.
     * - Delegates to `ConfigurationConfig::getEncryptionKey()` in the Shared layer.
     *
     * @api
     *
     * @return string
     */
    public function getEncryptionKey(): string
    {
        return $this->getSharedConfig()->getEncryptionKey();
    }

    /**
     * Specification:
     * - Returns the initialization vector used for encrypting and decrypting secret configuration values.
     * - Reads from environment configuration using `ConfigurationConstants::ENCRYPTION_INIT_VECTOR`.
     * - Delegates to `ConfigurationConfig::getEncryptionInitVector()` in the Shared layer.
     *
     * @api
     *
     * @return string
     */
    public function getEncryptionInitVector(): string
    {
        return $this->getSharedConfig()->getEncryptionInitVector();
    }
}
