<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace Spryker\Shared\Configuration;

use Spryker\Shared\Kernel\AbstractSharedConfig;

class ConfigurationConfig extends AbstractSharedConfig
{
    /**
     * Specification:
     * - Returns the encryption key used for encrypting and decrypting secret configuration values.
     * - Reads from environment configuration using `ConfigurationConstants::ENCRYPTION_KEY`.
     *
     * @api
     *
     * @return string
     */
    public function getEncryptionKey(): string
    {
        return $this->get(ConfigurationConstants::ENCRYPTION_KEY);
    }

    /**
     * Specification:
     * - Returns the initialization vector used for encrypting and decrypting secret configuration values.
     * - Reads from environment configuration using `ConfigurationConstants::ENCRYPTION_INIT_VECTOR`.
     *
     * @api
     *
     * @return string
     */
    public function getEncryptionInitVector(): string
    {
        return $this->get(ConfigurationConstants::ENCRYPTION_INIT_VECTOR);
    }

    /**
     * Specification:
     * - Returns the list of scope keys available for configuration management.
     * - Default: `['global']`. Override in project-level config to add scopes like `store`, `locale`.
     * - Determines which scopes are shown in the Backoffice scope selector.
     * - Used by both Zed and Client layers for scope resolution.
     *
     * @api
     *
     * @return array<string>
     */
    public function getAvailableScopes(): array
    {
        return [
            ConfigurationConstants::SCOPE_GLOBAL,
        ];
    }

    /**
     * Specification:
     * - Returns the scope hierarchy as an associative array where each key is a scope and the value is its parent scope.
     * - The root scope (global) has `null` as parent.
     * - Default: `['global' => null]`. Override to define hierarchy like `['store' => 'global', 'global' => null]`.
     * - Used for value inheritance resolution: values walk up this hierarchy until a value is found.
     *
     * @api
     *
     * @return array<string, string|null>
     */
    public function getScopeHierarchy(): array
    {
        return [
            ConfigurationConstants::SCOPE_GLOBAL => null,
        ];
    }

    /**
     * Specification:
     * - Returns the absolute file path where the merged configuration schema is cached as a PHP array.
     * - This file is generated by the `configuration:sync` console command.
     * - Read at runtime by both Zed (schema provider) and Client (storage reader) layers.
     *
     * @api
     *
     * @return string
     */
    public function getMergedSchemaFilePath(): string
    {
        return APPLICATION_ROOT_DIR . '/data/cache/configuration/merged-schema.php';
    }

    /**
     * Specification:
     * - Returns the absolute file path where the flat settings map is cached as a PHP array.
     * - This file is generated by the `configuration:sync` console command alongside the merged schema.
     * - Contains only runtime-critical setting metadata keyed by compound setting key for O(1) lookup.
     * - Read at runtime by both Zed (business models) and Client (storage reader) layers.
     *
     * @api
     *
     * @return string
     */
    public function getSettingsMapFilePath(): string
    {
        return APPLICATION_ROOT_DIR . '/data/cache/configuration/settings-map.php';
    }
}
